# Generated by Django 5.0.3 on 2024-03-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='', verbose_name='Загрузить файл')),
            ],
            options={
                'verbose_name': 'Текстовый файл',
                'verbose_name_plural': 'Текстовые файлы',
            },
        ),
    ]
